Games_library/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

games/urls.py
from django.urls import path

from games.views import (
    index,
    PublisherListView,
    PublisherDetailView,
    PublisherCreateView,
    PublisherUpdateView,
    PublisherDeleteView,
    GameListView,
    GameDetailView,
    GameCreateView,
    GameUpdateView,
    GameDeleteView,
    PlayerListView,
    PlayerDetailView,
    PlayerCreateView,
    PlayerUpdateView,
    PlayerDeleteView,
    ToggleAssignGame
)

app_name = "games"

urlpatterns = [
    path("", index, name="index"),
    path("publishers/", PublisherListView.as_view(), name="publishers-list"),
    path("publishers/<int:pk>/", PublisherDetailView.as_view(), name="publishers-detail"),
    path("publishers/create/", PublisherCreateView.as_view(), name="publishers-create"),
    path("publishers/update/<int:pk>/", PublisherUpdateView.as_view(), name="publishers-update"),
    path("publishers/delete/<int:pk>/", PublisherDeleteView.as_view(), name="publishers-delete"),

    path("games/", GameListView.as_view(), name="games-list"),
    path("games/<int:pk>/", GameDetailView.as_view(), name="games-detail"),
    path("games/create/", GameCreateView.as_view(), name="games-create"),
    path("games/update/<int:pk>/", GameUpdateView.as_view(), name="games-update"),
    path("games/delete/<int:pk>/", GameDeleteView.as_view(), name="games-delete"),
    path("games/<int:pk>/toggle-assign/", ToggleAssignGame.as_view(), name="toggle-game-assign"),

    path("players/", PlayerListView.as_view(), name="players-list"),
    path("players/<int:pk>/", PlayerDetailView.as_view(), name="players-detail"),
    path("players/create/", PlayerCreateView.as_view(), name="players-create"),
    path("players/update/<int:pk>/", PlayerUpdateView.as_view(), name="players-update"),
    path("players/delete/<int:pk>/", PlayerDeleteView.as_view(), name="players-delete"),
]

games_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("games.urls", namespace="games")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

templates/includes/footer-auth.html
<footer class="footer pt-5 mt-5">
  <div class="container">
    <div class=" row">
      <div class="col-md-3 mb-4 ms-auto">
        <div>
          <ul class="d-flex flex-row ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://t.me/KtoMuTo" target="_blank">
                <i class="fa fa-telegram text-lg opacity-8" aria-hidden="true"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://www.linkedin.com/in/volodymyr-кampanchenko-130b9a325/" target="_blank">
                <i class="fa fa-linkedin-square text-lg opacity-8" aria-hidden="true"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://github.com/D0mln0?tab=repositories" target="_blank">
                <i class="fab fa-github text-lg opacity-8"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer-components.html
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Company
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            About Us
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Team
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Products
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Blog
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Pricing
          </a>
        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-dribbble"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-twitter"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-instagram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-pinterest"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold" target="_blank">Creative Tim</a>
              coded by AppSeed.
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <div class="col-md-3 mb-4 ms-auto">
    <div>
      <ul class="d-flex flex-row ms-n3 nav">
        <li class="nav-item">
          <a class="nav-link pe-1" href="https://t.me/KtoMuTo" target="_blank">
            <i class="fa fa-telegram text-lg opacity-8" aria-hidden="true"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link pe-1" href="https://www.linkedin.com/in/volodymyr-кampanchenko-130b9a325/" target="_blank">
            <i class="fa fa-linkedin-square text-lg opacity-8" aria-hidden="true"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link pe-1" href="https://github.com/D0mln0?tab=repositories" target="_blank">
            <i class="fab fa-github text-lg opacity-8"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</footer>

templates/includes/navigation-transparent.html
  <!-- Navbar Transparent -->
  <nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3  navbar-transparent ">
    <div class="container">
      <a class="navbar-brand  text-white " href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
        Game Library
      </a>
    </div>
  </nav>
  <!-- End Navbar -->

templates/includes/navigation.html
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
             href="{% url 'games:index' %}"
             rel="tooltip"
             data-placement="bottom">
            Games Library
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center btn"
                   aria-expanded="false"
                   href="{% url 'games:games-list' %}"
                >
                  <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                  Games
                </a>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                   aria-expanded="false"
                   href="{% url 'games:publishers-list' %}"
                >
                  <i class="material-icons opacity-6 me-2 text-md">view_day</i>
                  Publishers
                </a>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                   aria-expanded="false"
                   href="{% url 'games:players-list' %}"
                >
                  <i class="material-icons opacity-6 me-2 text-md">article</i>
                  Players
                </a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" 
                    href="{% url 'login'%}?next={{request.path}}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
                  </a>
                </li> 
              {% else %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'login'%}?next={{request.path}}">
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign IN">Login</p>
                  </a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
{#  <section class="py-7">#}
  <div class="container">
    <div class="col-lg-4 mx-auto">
      <ul class="pagination pagination-lg m-4">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
          </li>
        {% endif %}
          <li class="page-item active" >
            <span class="page-link" >{{ page_obj.number }} of {{ paginator.num_pages }}</span>
          </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</section>

{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/sidebar.html
{% if user.is_authenticated %}
  <li class="list-group-item">
    User: 
    <a href="{{ user.get_absolute_url }}">
      {{ user.get_username }}
    </a>
  </li>
  <li class="list-group-item">
    <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
      {% csrf_token %}
      <button type="submit" style="border: none;background-color: transparent;">
        <i class="fa fa-sign-out" style="font-size:24px;color:red"></i>
      </button>
    </form>
  </li>
{% else %}
  <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
{% endif %}

<ul class="sidebar-nav">
  <li class="list-group-item"><a href="{% url 'games:index' %}">Home page</a></li>
  <li class="list-group-item"><a href="{% url 'games:publishers-list' %}">Publishers</a></li>
  <li class="list-group-item"><a href="{% url 'games:games-list' %}">Games</a></li>
  <li class="list-group-item"><a href="{% url 'games:players-list' %}">Players</a></li>
</ul>