Games_library/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

games/urls.py
from django.urls import path

from games.views import (
    index,
    PublisherListView,
    PublisherDetailView,
    PublisherCreateView,
    PublisherUpdateView,
    PublisherDeleteView,
    GameListView,
    GameDetailView,
    GameCreateView,
    GameUpdateView,
    GameDeleteView,
    PlayerListView,
    PlayerDetailView,
    PlayerCreateView,
    PlayerUpdateView,
    PlayerDeleteView,
    ToggleAssignGame
)

app_name = "games"

urlpatterns = [
    path("", index, name="index"),
    path("publishers/", PublisherListView.as_view(), name="publishers-list"),
    path("publishers/<int:pk>/", PublisherDetailView.as_view(), name="publishers-detail"),
    path("publishers/create/", PublisherCreateView.as_view(), name="publishers-create"),
    path("publishers/update/<int:pk>/", PublisherUpdateView.as_view(), name="publishers-update"),
    path("publishers/delete/<int:pk>/", PublisherDeleteView.as_view(), name="publishers-delete"),

    path("games/", GameListView.as_view(), name="games-list"),
    path("games/<int:pk>/", GameDetailView.as_view(), name="games-detail"),
    path("games/create/", GameCreateView.as_view(), name="games-create"),
    path("games/update/<int:pk>/", GameUpdateView.as_view(), name="games-update"),
    path("games/delete/<int:pk>/", GameDeleteView.as_view(), name="games-delete"),
    path("games/<int:pk>/toggle-assign/", ToggleAssignGame.as_view(), name="toggle-game-assign"),

    path("players/", PlayerListView.as_view(), name="players-list"),
    path("players/<int:pk>/", PlayerDetailView.as_view(), name="players-detail"),
    path("players/create/", PlayerCreateView.as_view(), name="players-create"),
    path("players/update/<int:pk>/", PlayerUpdateView.as_view(), name="players-update"),
    path("players/delete/<int:pk>/", PlayerDeleteView.as_view(), name="players-delete"),
]

games_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("games.urls", namespace="games")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

games/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Publisher(models.Model):
    name = models.CharField(max_length=255)
    info = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField(max_length=255)
    year = models.IntegerField()
    publishers = models.ForeignKey(
        Publisher,
        on_delete=models.CASCADE
    )
    players = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="games"
    )

    def __str__(self):
        return f"{self.publishers}: {self.name}"


class Player(AbstractUser):

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("games:players-detail", kwargs={"pk": self.pk})

games/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from games.models import Game, Player


class GameForm(forms.ModelForm):
    players = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Game
        fields = "__all__"

    def clean_year(self):
        year = self.cleaned_data["year"]
        if year < 1958:
            raise ValidationError("The first game ever was created in 1958, so year of your game must be at least 1958")
        return year


class PlayerForm(UserCreationForm):
    class Meta:
        model = Player
        fields = UserCreationForm.Meta.fields + (
            "email",
            "first_name",
            "last_name",
        )


class PlayerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        ),
    )


class GameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by game name"}
        )
    )


class PublisherSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by publisher name"}
        )
    )

games/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View

from games.forms import GameForm, PlayerForm, PublisherSearchForm, GameSearchForm, PlayerSearchForm
from games.models import Game, Player, Publisher
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


def index(request: HttpRequest) -> HttpResponse:
    context = {
        "games": Game.objects.count(),
        "publishers": Publisher.objects.count(),
        "players": Player.objects.count(),
    }
    return render(request, "games/index.html", context=context)


class PublisherListView(LoginRequiredMixin, ListView):
    model = Publisher
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PublisherListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PublisherSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return self.model.objects.filter(name__icontains=name)
        return self.model.objects.all()


class PublisherDetailView(LoginRequiredMixin, DetailView):
    model = Publisher


class PublisherCreateView(LoginRequiredMixin, CreateView):
    model = Publisher
    fields = "__all__"
    template_name = "games/publisher_form.html"
    success_url = reverse_lazy("games:publishers-list")


class PublisherUpdateView(LoginRequiredMixin, UpdateView):
    model = Publisher
    fields = "__all__"
    success_url = reverse_lazy("games:publishers-list")


class PublisherDeleteView(LoginRequiredMixin, DeleteView):
    model = Publisher
    success_url = reverse_lazy("games:publishers-list")


class GameListView(LoginRequiredMixin, ListView):
    model = Game
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = GameSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Game.objects.select_related("publishers")
        name = self.request.GET.get("name")
        if name:
            return self.model.objects.filter(name__icontains=name)
        return queryset


class GameDetailView(LoginRequiredMixin, DetailView):
    model = Game
    queryset = Game.objects.prefetch_related("players")


class GameCreateView(LoginRequiredMixin, CreateView):
    form_class = GameForm
    template_name = "games/game_form.html"
    success_url = reverse_lazy("games:games-list")


class GameUpdateView(LoginRequiredMixin, UpdateView):
    model = Game
    form_class = GameForm
    template_name = "games/game_form.html"
    success_url = reverse_lazy("games:games-list")


class GameDeleteView(LoginRequiredMixin, DeleteView):
    model = Game
    success_url = reverse_lazy("games:games-list")


class PlayerListView(LoginRequiredMixin, ListView):
    model = Player
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PlayerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = PlayerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        username = self.request.GET.get("username")
        if username:
            return self.model.objects.filter(username__icontains=username)
        return self.model.objects.all()


class PlayerDetailView(LoginRequiredMixin, DetailView):
    model = Player
    queryset = Player.objects.prefetch_related("games__publishers")


class PlayerCreateView(CreateView):
    model = Player
    form_class = PlayerForm
    template_name = "games/player_form.html"
    success_url = reverse_lazy("games:players-list")


class PlayerUpdateView(LoginRequiredMixin, UpdateView):
    model = Player
    form_class = PlayerForm
    template_name = "games/player_form.html"
    success_url = reverse_lazy("games:players-list")


class PlayerDeleteView(LoginRequiredMixin, DeleteView):
    model = Player
    success_url = reverse_lazy("games:players-list")


class ToggleAssignGame(View):
    model = Game

    def post(self, request: HttpRequest, pk: int, *args, **kwargs) -> HttpResponse:
        player = Player.objects.get(id=request.user.id)
        if self.model.objects.get(id=pk) in player.games.all():
            player.games.remove(pk)
        else:
            player.games.add(pk)
        return HttpResponseRedirect(reverse_lazy("games:games-detail", kwargs={"pk": pk}))

templates/games/game_detail.html
{% extends "layouts/base_without_footer.html" %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% include 'includes/navigation.html' %}

<div style="background-color: #f4ebeb">
  <div class="page-header min-vh-90">
    <div class="container" style="margin-top: 70px">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center mx-auto my-auto">
          <h1 class="text-dark">{{ game.name }} details</h1>
          <p>Release year: {{ game.year }}</p>
        </div>
      </div>
      <hr>
      <ul>
        <li>
          <p>
            Publisher: 
            <a href="{% url 'games:publishers-detail' pk=game.publishers.id %}">
              {{ game.publishers.name }}
            </a>
          </p>
        </li>
      </ul>
      {% if game.players %}
      <hr>
      <h5>Players:</h5>
        <form action="/games/{{ game.id }}/toggle-assign/" method="post">
        {% csrf_token %}
        {{ form.as_p }}
          {% if game in user.games.all %}
            <button type="submit" class="btn btn-danger link-to-page">
                I don`t play this game anymore
            </button>
          {% else %}
            <button type="submit" class="btn btn-success link-to-page">
                I play this game too
            </button>
          {% endif %}
        </form>
      <ol>
        {% for player in game.players.all %}
          <li>
              <a href="{% url 'games:players-detail' pk=player.id %}">{{ player.username }}</a>
          </li>
        {% endfor %}
      </ol>  
      {% else %}
        <p><i>Nobody is playing this game yet</i></p>
      {% endif %}
      {% if user.is_staff %}
        <div class="form-inline">
          <a href="{% url 'games:games-delete' pk=game.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>
  
          <a href="{% url 'games:games-update' pk=game.id %}" class="btn btn-secondary link-to-page">
            Update
          </a>
        </div>
      {% endif %}
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    // get the element to animate
    var element = document.getElementById('count-stats');
    var elementHeight = element.clientHeight;

    // listen for scroll event and call animate function

    document.addEventListener('scroll', animate);

    // check if element is in view
    function inView() {
      // get window height
      var windowHeight = window.innerHeight;
      // get number of pixels that the document is scrolled
      var scrollY = window.scrollY || window.pageYOffset;
      // get current scroll position (distance from the top of the page to the bottom of the current viewport)
      var scrollPosition = scrollY + windowHeight;
      // get element position (distance from the top of the page to the bottom of the element)
      var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

      // is scroll position greater than element position? (is element in view?)
      if (scrollPosition > elementPosition) {
        return true;
      }

      return false;
    }

    var animateComplete = true;
    // animate element when it is in view
    function animate() {

      // is element in view?
      if (inView()) {
        if (animateComplete) {
          if (document.getElementById('state1')) {
            const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
            if (!countUp.error) {
              countUp.start();
            } else {
              console.error(countUp.error);
            }
          }
          if (document.getElementById('state2')) {
            const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
            if (!countUp1.error) {
              countUp1.start();
            } else {
              console.error(countUp1.error);
            }
          }
          if (document.getElementById('state3')) {
            const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
            if (!countUp2.error) {
              countUp2.start();
            } else {
              console.error(countUp2.error);
            };
          }
          animateComplete = false;
        }
      }
    }

    if (document.getElementById('typed')) {
      var typed = new Typed("#typed", {
        stringsElement: '#typed-strings',
        typeSpeed: 90,
        backSpeed: 90,
        backDelay: 200,
        startDelay: 500,
        loop: true
      });
    }
  </script>

  <script>
    if (document.getElementsByClassName('page-header')) {
      window.onscroll = debounce(function() {
        var scrollPosition = window.pageYOffset;
        var bgParallax = document.querySelector('.page-header');
        var oVal = (window.scrollY / 3);
        bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
      }, 6);
    }
  </script>

{% endblock javascripts %}

templates/games/game_form.html
{% extends "layouts/base-fullscreen.html" %}


<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include 'includes/navigation-transparent.html' %}
  <div class="page-header align-items-start min-vh-100" style="background-image: url('{{ ASSETS_ROOT }}/img/illustrations/dark-fantasy-pixel-art.png');" loading="lazy">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-8 col-md-8 col-12 mx-auto">
          <div class="card z-index-0 fadeIn3 fadeInBottom">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">
                  Game {{ object|yesno:"Update,Create" }}
                </h4>
                <div class="row mt-3">
                  <p class="mb-0 text-white text-center">
                    {% if msg %}
                      {{ msg | safe }}
                    {% endif %}
                  </p>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form role="form" method="post" action="">

                {% csrf_token %}
                {{ form.as_p }}

                <div class="text-center">
                  <button type="submit" name="register"
                          class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                    {{ object|yesno:"Update,Create" }}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% include 'includes/footer-auth.html' %}

  </div>
{% endblock %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/games/player_detail.html
{% extends "layouts/base_without_footer.html" %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% include 'includes/navigation.html' %}

<div style="background-color: #f4ebeb">
  <div class="page-header min-vh-90">
    <div class="container" style="margin-top: 70px">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center mx-auto my-auto">
          <h1 class="text-dark">{{ player.username }} details</h1>
        </div>
      </div>
      {% if player.first_name and player.last_name %}
        <p>Full name: {{ player.get_full_name }}</p>
      {% endif %}
      {% if player.games.all %}
        <hr>
        <h5>Games</h5>
        <ol>
          {% for game in player.games.all %}
            <li>
                <a href="{% url 'games:games-detail' pk=game.id %}">{{ game.name }}</a>
            </li>
          {% endfor %}
        </ol>
      {% else %}
        <hr>
        <p><i>This person doesn't play games (yet)</i></p>
      {% endif %}
      {% if user.is_staff %}
        <div class="form-inline">
          <a href="{% url 'games:players-delete' pk=player.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>
        </div>
      {% endif %}
      {% if user == player %}
        <div class="form-inline">
          <a href="{% url 'games:players-update' pk=player.id %}" class="btn btn-secondary link-to-page">
            Update
          </a>
        </div>
      {% endif %}
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    // get the element to animate
    var element = document.getElementById('count-stats');
    var elementHeight = element.clientHeight;

    // listen for scroll event and call animate function

    document.addEventListener('scroll', animate);

    // check if element is in view
    function inView() {
      // get window height
      var windowHeight = window.innerHeight;
      // get number of pixels that the document is scrolled
      var scrollY = window.scrollY || window.pageYOffset;
      // get current scroll position (distance from the top of the page to the bottom of the current viewport)
      var scrollPosition = scrollY + windowHeight;
      // get element position (distance from the top of the page to the bottom of the element)
      var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

      // is scroll position greater than element position? (is element in view?)
      if (scrollPosition > elementPosition) {
        return true;
      }

      return false;
    }

    var animateComplete = true;
    // animate element when it is in view
    function animate() {

      // is element in view?
      if (inView()) {
        if (animateComplete) {
          if (document.getElementById('state1')) {
            const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
            if (!countUp.error) {
              countUp.start();
            } else {
              console.error(countUp.error);
            }
          }
          if (document.getElementById('state2')) {
            const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
            if (!countUp1.error) {
              countUp1.start();
            } else {
              console.error(countUp1.error);
            }
          }
          if (document.getElementById('state3')) {
            const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
            if (!countUp2.error) {
              countUp2.start();
            } else {
              console.error(countUp2.error);
            };
          }
          animateComplete = false;
        }
      }
    }

    if (document.getElementById('typed')) {
      var typed = new Typed("#typed", {
        stringsElement: '#typed-strings',
        typeSpeed: 90,
        backSpeed: 90,
        backDelay: 200,
        startDelay: 500,
        loop: true
      });
    }
  </script>

  <script>
    if (document.getElementsByClassName('page-header')) {
      window.onscroll = debounce(function() {
        var scrollPosition = window.pageYOffset;
        var bgParallax = document.querySelector('.page-header');
        var oVal = (window.scrollY / 3);
        bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
      }, 6);
    }
  </script>

{% endblock javascripts %}

templates/games/publisher_detail.html
{% extends "layouts/base_without_footer.html" %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% include 'includes/navigation.html' %}

<div style="background-color: #f4ebeb">
  <div class="page-header min-vh-90">
    <div class="container" style="margin-top: 70px">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center mx-auto my-auto">
          <h1 class="text-dark">{{ publisher.name }} details</h1>
          <p>{{ publisher.info }}</p>
        </div>
      </div>
      <hr>
      {% if publisher.game_set %}
        <ul>
          {% for games in publisher.game_set.all %}
            <li><a href="{% url 'games:games-detail' pk=games.id %}">{{ games.name }}</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <p><i>Information about publisher not found yet</i></p>
      {% endif %}
      {% if user.is_staff %}
        <div class="form-inline">
          <a href="{% url 'games:publishers-delete' pk=publisher.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>
      
          <a href="{% url 'games:publishers-update' pk=publisher.id %}" class="btn btn-secondary link-to-page">
            Update
          </a>
        </div>
      {% endif %}
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    // get the element to animate
    var element = document.getElementById('count-stats');
    var elementHeight = element.clientHeight;

    // listen for scroll event and call animate function

    document.addEventListener('scroll', animate);

    // check if element is in view
    function inView() {
      // get window height
      var windowHeight = window.innerHeight;
      // get number of pixels that the document is scrolled
      var scrollY = window.scrollY || window.pageYOffset;
      // get current scroll position (distance from the top of the page to the bottom of the current viewport)
      var scrollPosition = scrollY + windowHeight;
      // get element position (distance from the top of the page to the bottom of the element)
      var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

      // is scroll position greater than element position? (is element in view?)
      if (scrollPosition > elementPosition) {
        return true;
      }

      return false;
    }

    var animateComplete = true;
    // animate element when it is in view
    function animate() {

      // is element in view?
      if (inView()) {
        if (animateComplete) {
          if (document.getElementById('state1')) {
            const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
            if (!countUp.error) {
              countUp.start();
            } else {
              console.error(countUp.error);
            }
          }
          if (document.getElementById('state2')) {
            const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
            if (!countUp1.error) {
              countUp1.start();
            } else {
              console.error(countUp1.error);
            }
          }
          if (document.getElementById('state3')) {
            const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
            if (!countUp2.error) {
              countUp2.start();
            } else {
              console.error(countUp2.error);
            };
          }
          animateComplete = false;
        }
      }
    }

    if (document.getElementById('typed')) {
      var typed = new Typed("#typed", {
        stringsElement: '#typed-strings',
        typeSpeed: 90,
        backSpeed: 90,
        backDelay: 200,
        startDelay: 500,
        loop: true
      });
    }
  </script>

  <script>
    if (document.getElementsByClassName('page-header')) {
      window.onscroll = debounce(function() {
        var scrollPosition = window.pageYOffset;
        var bgParallax = document.querySelector('.page-header');
        var oVal = (window.scrollY / 3);
        bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
      }, 6);
    }
  </script>

{% endblock javascripts %}

templates/games/publisher_list.html
{% extends "layouts/base_without_footer.html" %}
{% load crispy_forms_filters %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% include 'includes/navigation.html' %}

<div style="background-color: #f4ebeb">
  <div class="page-header min-vh-90">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center mx-auto my-auto">
          <h1 class="text-dark">Here we have publishers</h1>
          <form  class="text-dark" method="get" action="" class="form-inline">
            {{ search_form|crispy }}
            <input type="submit" value="Find" class="btn btn-secondary">
          </form>
        </div>
      </div>
      
      {% if publisher_list %}
        <ul>
          {% for publisher in publisher_list %}
            <li style="list-style-type: none;"><a class="text-dark" href="{% url 'games:publishers-detail' pk=publisher.id %}">{{ publisher.name }}</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <p><i>Publishers not found</i></p>
      {% endif %}
      <a href="{% url 'games:publishers-create' %}" class="btn bg-white text-dark">
          Add new Publisher
      </a>
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    // get the element to animate
    var element = document.getElementById('count-stats');
    var elementHeight = element.clientHeight;

    // listen for scroll event and call animate function

    document.addEventListener('scroll', animate);

    // check if element is in view
    function inView() {
      // get window height
      var windowHeight = window.innerHeight;
      // get number of pixels that the document is scrolled
      var scrollY = window.scrollY || window.pageYOffset;
      // get current scroll position (distance from the top of the page to the bottom of the current viewport)
      var scrollPosition = scrollY + windowHeight;
      // get element position (distance from the top of the page to the bottom of the element)
      var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

      // is scroll position greater than element position? (is element in view?)
      if (scrollPosition > elementPosition) {
        return true;
      }

      return false;
    }

    var animateComplete = true;
    // animate element when it is in view
    function animate() {

      // is element in view?
      if (inView()) {
        if (animateComplete) {
          if (document.getElementById('state1')) {
            const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
            if (!countUp.error) {
              countUp.start();
            } else {
              console.error(countUp.error);
            }
          }
          if (document.getElementById('state2')) {
            const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
            if (!countUp1.error) {
              countUp1.start();
            } else {
              console.error(countUp1.error);
            }
          }
          if (document.getElementById('state3')) {
            const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
            if (!countUp2.error) {
              countUp2.start();
            } else {
              console.error(countUp2.error);
            };
          }
          animateComplete = false;
        }
      }
    }

    if (document.getElementById('typed')) {
      var typed = new Typed("#typed", {
        stringsElement: '#typed-strings',
        typeSpeed: 90,
        backSpeed: 90,
        backDelay: 200,
        startDelay: 500,
        loop: true
      });
    }
  </script>

  <script>
    if (document.getElementsByClassName('page-header')) {
      window.onscroll = debounce(function() {
        var scrollPosition = window.pageYOffset;
        var bgParallax = document.querySelector('.page-header');
        var oVal = (window.scrollY / 3);
        bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
      }, 6);
    }
  </script>

{% endblock javascripts %}